/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 09-sept.-2018 23:01:52 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS comments_id_seq
;

DROP SEQUENCE IF EXISTS element_id_seq
;

DROP SEQUENCE IF EXISTS gps_coordinates_id_seq
;

DROP SEQUENCE IF EXISTS parking_id_seq
;

DROP SEQUENCE IF EXISTS user_role_id_seq
;

DROP SEQUENCE IF EXISTS users_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS area CASCADE
;

DROP TABLE IF EXISTS areas_in_atlases CASCADE
;

DROP TABLE IF EXISTS atlas CASCADE
;

DROP TABLE IF EXISTS comments CASCADE
;

DROP TABLE IF EXISTS crag CASCADE
;

DROP TABLE IF EXISTS crags_in_atlases CASCADE
;

DROP TABLE IF EXISTS element CASCADE
;

DROP TABLE IF EXISTS gps_coordinates CASCADE
;

DROP TABLE IF EXISTS parking CASCADE
;

DROP TABLE IF EXISTS pitch CASCADE
;

DROP TABLE IF EXISTS route CASCADE
;

DROP TABLE IF EXISTS user_role CASCADE
;

DROP TABLE IF EXISTS users CASCADE
;

/* Create Tables */

CREATE TABLE area
(
	element_id integer NOT NULL,
	approach_duration integer NOT NULL,
	locality varchar(1000) NOT NULL
)
;

CREATE TABLE areas_in_atlases
(
	atlas_id integer NOT NULL,
	area_id integer NOT NULL
)
;

CREATE TABLE atlas
(
	element_id integer NOT NULL,
	available boolean NOT NULL,
	user_id integer NULL
)
;

CREATE TABLE comments
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"comments_id_seq"'::text)::regclass),
	title varchar(100) NULL,
	content varchar(1000) NOT NULL,
	create_date timestamp without time zone NOT NULL,
	update_date timestamp without time zone NULL,
	user_id integer NOT NULL,
	element_id integer NOT NULL
)
;

CREATE TABLE crag
(
	element_id integer NOT NULL,
	map_url varchar NULL,
	rock_type varchar(50) NULL,
	area_id integer NULL
)
;

CREATE TABLE crags_in_atlases
(
	atlas_id integer NOT NULL,
	crag_id integer NOT NULL
)
;

CREATE TABLE element
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"element_id_seq"'::text)::regclass),
	name varchar(50) NULL,
	create_date timestamp without time zone NOT NULL,
	update_date timestamp without time zone NULL
)
;

CREATE TABLE gps_coordinates
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"gps_coordinates_id_seq"'::text)::regclass),
	latitude numeric(9,6) NOT NULL,
	longitude numeric(9,6) NOT NULL,
	altitude integer NULL,
	crag_id integer NULL,
	parking_id integer NULL
)
;

CREATE TABLE parking
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"parking_id_seq"'::text)::regclass),
	indication varchar(1000) NOT NULL,
	area_id integer NULL,
	crag_id integer NULL
)
;

CREATE TABLE pitch
(
	element_id integer NOT NULL,
	grade varchar(3) NULL,
	length integer NULL,
	nb_anchor integer NULL,
	nb_meters_between_anchors double precision NULL,
	route_id integer NOT NULL
)
;

CREATE TABLE route
(
	element_id integer NOT NULL,
	grade varchar(3) NULL,
	length integer NULL,
	nb_anchor integer NULL,
	nb_meters_between_anchors double precision NULL,
	multi_pitch boolean NOT NULL   DEFAULT false,
	crag_id integer NOT NULL
)
;

CREATE TABLE user_role
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"user_role_id_seq"'::text)::regclass),
	role varchar(20) NOT NULL,
	user_id integer NULL
)
;

CREATE TABLE users
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"users_id_seq"'::text)::regclass),
	email varchar(100) NOT NULL,
	password varchar(250) NOT NULL,
	first_name varchar(100) NOT NULL,
	last_name varchar(100) NOT NULL,
	user_name varchar(20) NOT NULL,
	gender varchar(10) NULL,
	email_visible boolean NOT NULL,
	date_of_birth time without time zone NULL,
	create_account_date timestamp without time zone NOT NULL,
	grade_max varchar(3) NULL,
	grade_first_attempt varchar(3) NULL,
	grade_average varchar(3) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE area ADD CONSTRAINT "PK_Area"
	PRIMARY KEY (element_id)
;

ALTER TABLE atlas ADD CONSTRAINT "PK_Atlas"
	PRIMARY KEY (element_id)
;

ALTER TABLE comments ADD CONSTRAINT "PK_Comment"
	PRIMARY KEY (id)
;

ALTER TABLE crag ADD CONSTRAINT "PK_Crag"
	PRIMARY KEY (element_id)
;

ALTER TABLE element ADD CONSTRAINT "PK_Element"
	PRIMARY KEY (id)
;

ALTER TABLE gps_coordinates ADD CONSTRAINT "PK_Gpscoordinates"
	PRIMARY KEY (id)
;

ALTER TABLE parking ADD CONSTRAINT "PK_Parking"
	PRIMARY KEY (id)
;

ALTER TABLE pitch ADD CONSTRAINT "PK_Pitch"
	PRIMARY KEY (element_id)
;

ALTER TABLE route ADD CONSTRAINT "PK_Route"
	PRIMARY KEY (element_id)
;

ALTER TABLE user_role ADD CONSTRAINT "PK_role"
	PRIMARY KEY (id)
;

ALTER TABLE users ADD CONSTRAINT "PK_User"
	PRIMARY KEY (id)
;

ALTER TABLE users 
  ADD CONSTRAINT "Email" UNIQUE (email)
;

ALTER TABLE users 
  ADD CONSTRAINT "Username" UNIQUE (user_name)
;

/* Create Foreign Key Constraints */

ALTER TABLE area ADD CONSTRAINT "FK_Area_Element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE areas_in_atlases ADD CONSTRAINT "FK_Atlas_owns"
	FOREIGN KEY (atlas_id) REFERENCES atlas (element_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE areas_in_atlases ADD CONSTRAINT "FK_Area_assigned"
	FOREIGN KEY (area_id) REFERENCES area (element_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE atlas ADD CONSTRAINT "FK_Atlas_Element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE atlas ADD CONSTRAINT "FK_Atlas_owns"
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE comments ADD CONSTRAINT "FK_comment_assigned"
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE comments ADD CONSTRAINT "FK_comment_element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE crag ADD CONSTRAINT "FK_Crag_composed"
	FOREIGN KEY (area_id) REFERENCES area (element_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE crag ADD CONSTRAINT "FK_Crag_Element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE crags_in_atlases ADD CONSTRAINT "FK_cragsInAtlas_atlas"
	FOREIGN KEY (atlas_id) REFERENCES atlas (element_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE crags_in_atlases ADD CONSTRAINT "FK_cragsInAtlas_crag"
	FOREIGN KEY (crag_id) REFERENCES crag (element_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE gps_coordinates ADD CONSTRAINT "FK_gpsCoordinates_crag"
	FOREIGN KEY (crag_id) REFERENCES crag (element_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE gps_coordinates ADD CONSTRAINT "FK_Gpscoordinates_Parking"
	FOREIGN KEY (parking_id) REFERENCES parking (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE parking ADD CONSTRAINT "FK_parking_area"
	FOREIGN KEY (area_id) REFERENCES area (element_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE parking ADD CONSTRAINT "FK_parking_crag"
	FOREIGN KEY (crag_id) REFERENCES crag (element_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE pitch ADD CONSTRAINT "FK_Pitch_Element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE pitch ADD CONSTRAINT "FK_Pitch_composed"
	FOREIGN KEY (route_id) REFERENCES route (element_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE route ADD CONSTRAINT "FK_Route_composed"
	FOREIGN KEY (crag_id) REFERENCES crag (element_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE route ADD CONSTRAINT "FK_Route_Element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE user_role ADD CONSTRAINT "FK_role_users"
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE comments_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE element_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE gps_coordinates_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE parking_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE user_role_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE users_id_seq INCREMENT 1 START 1
;
