/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.0 		*/
/*  Created On : 23-nov.-2018 16:27:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS booking_request_id_seq
;

DROP SEQUENCE IF EXISTS comments_id_seq
;

DROP SEQUENCE IF EXISTS element_id_seq
;

DROP SEQUENCE IF EXISTS role_id_seq
;

DROP SEQUENCE IF EXISTS users_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS area CASCADE
;

DROP TABLE IF EXISTS atlas CASCADE
;

DROP TABLE IF EXISTS booking_request CASCADE
;

DROP TABLE IF EXISTS comments CASCADE
;

DROP TABLE IF EXISTS crag CASCADE
;

DROP TABLE IF EXISTS element CASCADE
;

DROP TABLE IF EXISTS pitch CASCADE
;

DROP TABLE IF EXISTS role CASCADE
;

DROP TABLE IF EXISTS roles_of_users CASCADE
;

DROP TABLE IF EXISTS route CASCADE
;

DROP TABLE IF EXISTS users CASCADE
;

/* Create Tables */

CREATE TABLE area
(
	element_id integer NOT NULL,
	approach_duration integer NOT NULL,
	nearest_city varchar(100) NOT NULL,
	access varchar(1000) NOT NULL,
	rock_type varchar(50) NULL,
	atlas_id integer NULL,
	altitude integer NULL,
	parking_access varchar(1000) NULL
)
;

CREATE TABLE atlas
(
	element_id integer NOT NULL,
	available boolean NOT NULL,
	user_id integer NULL,
	country varchar(50) NOT NULL,
	region varchar(50) NOT NULL,
	department varchar(50) NULL
)
;

CREATE TABLE booking_request
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"booking_request_id_seq"'::text)::regclass),
	start_date date NOT NULL,
	end_date date NOT NULL,
	user_emitter_id integer NOT NULL,
	atlas_id integer NOT NULL,
	message varchar(1000) NULL,
	accepted boolean NULL,
	create_date timestamp without time zone NULL
)
;

CREATE TABLE comments
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"comments_id_seq"'::text)::regclass),
	title varchar(50) NOT NULL,
	content varchar(3000) NOT NULL,
	create_date timestamp without time zone NOT NULL,
	user_id integer NOT NULL,
	element_id integer NOT NULL
)
;

CREATE TABLE crag
(
	element_id integer NOT NULL,
	area_id integer NULL,
	access varchar(1000) NULL,
	approach_duration integer NULL
)
;

CREATE TABLE element
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"element_id_seq"'::text)::regclass),
	name varchar(50) NULL,
	create_date timestamp without time zone NOT NULL,
	update_date timestamp without time zone NULL
)
;

CREATE TABLE pitch
(
	element_id integer NOT NULL,
	grade varchar(3) NOT NULL,
	length integer NOT NULL,
	nb_anchor integer NULL,
	route_id integer NULL,
	verticality varchar(50) NULL,
	style varchar(50) NULL
)
;

CREATE TABLE role
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"role_id_seq"'::text)::regclass),
	role varchar(20) NOT NULL
)
;

CREATE TABLE roles_of_users
(
	user_id integer NULL,
	role_id integer NULL
)
;

CREATE TABLE route
(
	element_id integer NOT NULL,
	grade varchar(3) NOT NULL,
	length integer NOT NULL,
	nb_anchor integer NULL,
	crag_id integer NULL,
	verticality varchar(50) NULL,
	style varchar(50) NULL
)
;

CREATE TABLE users
(
	id integer NOT NULL   DEFAULT NEXTVAL(('"users_id_seq"'::text)::regclass),
	email varchar(100) NOT NULL,
	password varchar(250) NOT NULL,
	first_name varchar(100) NOT NULL,
	last_name varchar(100) NOT NULL,
	user_name varchar(20) NOT NULL,
	gender varchar(10) NULL,
	email_visible boolean NOT NULL,
	date_of_birth date NULL,
	create_account_date timestamp without time zone NOT NULL,
	grade_average varchar(3) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE area ADD CONSTRAINT "PK_Area"
	PRIMARY KEY (element_id)
;

ALTER TABLE atlas ADD CONSTRAINT "PK_Atlas"
	PRIMARY KEY (element_id)
;

ALTER TABLE booking_request ADD CONSTRAINT "PK_booking_request"
	PRIMARY KEY (id)
;

ALTER TABLE comments ADD CONSTRAINT "PK_Message"
	PRIMARY KEY (id)
;

ALTER TABLE crag ADD CONSTRAINT "PK_Crag"
	PRIMARY KEY (element_id)
;

ALTER TABLE element ADD CONSTRAINT "PK_Element"
	PRIMARY KEY (id)
;

ALTER TABLE pitch ADD CONSTRAINT "PK_Pitch"
	PRIMARY KEY (element_id)
;

ALTER TABLE role ADD CONSTRAINT "PK_role"
	PRIMARY KEY (id)
;

ALTER TABLE role 
  ADD CONSTRAINT role_unique UNIQUE (role)
;

ALTER TABLE route ADD CONSTRAINT "PK_Route"
	PRIMARY KEY (element_id)
;

ALTER TABLE users ADD CONSTRAINT "PK_User"
	PRIMARY KEY (id)
;

ALTER TABLE users 
  ADD CONSTRAINT "Email" UNIQUE (email)
;

ALTER TABLE users 
  ADD CONSTRAINT "Username" UNIQUE (user_name)
;

/* Create Foreign Key Constraints */

ALTER TABLE area ADD CONSTRAINT "FK_area_atlas"
	FOREIGN KEY (atlas_id) REFERENCES atlas (element_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE area ADD CONSTRAINT "FK_Area_Element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE atlas ADD CONSTRAINT "FK_atlas_users"
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE atlas ADD CONSTRAINT "FK_Atlas_Element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE booking_request ADD CONSTRAINT "FK_booking_request_atlas"
	FOREIGN KEY (atlas_id) REFERENCES atlas (element_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE booking_request ADD CONSTRAINT "FK_booking_request_users"
	FOREIGN KEY (user_emitter_id) REFERENCES users (id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE comments ADD CONSTRAINT "FK_communication_element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE comments ADD CONSTRAINT "FK_communication_users"
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE crag ADD CONSTRAINT "FK_Crag_composed"
	FOREIGN KEY (area_id) REFERENCES area (element_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE crag ADD CONSTRAINT "FK_Crag_Element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE pitch ADD CONSTRAINT "FK_Pitch_Element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE pitch ADD CONSTRAINT "FK_Pitch_composed"
	FOREIGN KEY (route_id) REFERENCES route (element_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE roles_of_users ADD CONSTRAINT "FK_roles_of_users_role"
	FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE roles_of_users ADD CONSTRAINT "FK_roles_of_users_users"
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE route ADD CONSTRAINT "FK_Route_composed"
	FOREIGN KEY (crag_id) REFERENCES crag (element_id) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE route ADD CONSTRAINT "FK_Route_Element"
	FOREIGN KEY (element_id) REFERENCES element (id) ON DELETE Cascade ON UPDATE Cascade
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE booking_request_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE comments_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE element_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE role_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE users_id_seq INCREMENT 1 START 1
;
